username: "r"
email: "reginaldbeakes@gmail.com"
ssh_key_filename: "id_rsa"
config: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG') }}"
home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
personal: "{{ home }}/personal"
go_version: "1.22.2"
go_architecture: "amd64"
nodejs_version: "20.12.1"
